ecoberry/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ecoberry.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', include ('powermonitorweb.urls')), # This must not have a namespace, otherwise it breaks the password reset
    url(r'^powermonitorweb/', include('powermonitorweb.urls', namespace='powermonitorweb')),
    url(r'^admin/', include(admin.site.urls)),
)

'''if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
         'serve', {'document_root': settings.MEDIA_ROOT}),
    )'''

powermonitorweb/urls.py
from django.conf.urls import patterns, url
from powermonitorweb import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^setup_household/$', views.setup_household, name='setup_household'),
                       url(r'^manage_social_media/$', views.manage_social_media, name='manage_social_media'),
                       url(r'^auth_social_media/$', views.auth_social_media, name='auth_social_media'),
                       url(r'^manage_reports/$', views.manage_reports, name='manage_reports'),
                       url(r'^manage_alerts/$', views.manage_alerts, name='manage_alerts'),
                       url(r'^login/$', views.user_login, name='login'),
                       url(r'^logout/$', views.user_logout, name='logout'),
                       url(r'^change_password/$', views.change_password, name='change_password'),
                       url(r'^manage_users/$', views.manage_users, name='manage_users'),
                       url(r'^add_user/$', views.add_user, name='add_user'),
                       url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                           views.reset_password_confirm, name='reset_password_confirm'),
                       url(r'^reset_password/$', views.reset_password, name='reset_password'),
                       url(r'^reset_password_complete/$', views.reset_password_complete,
                           name='reset_password_complete'),
                       url(r'^profile/$', views.profile, name='profile'),
                       url(r'^graphs/$', views.graphs, name='graphs')
                       )

powermonitorweb/models.py
from django.db import models
from django.contrib.auth.models import User
from powermonitorweb.fields import UnixTimestampField


class Readings(models.Model):
    """
    Stores electricity readings from the power monitoring circuit
    """
    time = UnixTimestampField(auto_now_add=True, auto_created=True, primary_key=True, null=False)
    reading = models.FloatField()


class Alert(models.Model):
    """
    Alert model. Stores descriptions for each alert.
    """
    # UserAlerts must be defined with quotes because the class is only defined after this class
    users = models.ManyToManyField(User, through='UserAlerts')
    alert_name = models.CharField(max_length=128)
    alert_description = models.CharField(max_length=255)

    def __unicode__(self):
        return self.alert_description

class UserAlerts(models.Model):
    """
    Association class for Alert and UserProfile
    """
    user_id = models.ForeignKey(User)
    alert_id = models.ForeignKey(Alert)


class AlertTip(models.Model):
    """
    Tips for alerts
    """
    alerts = models.ManyToManyField(Alert)
    tip_description = models.CharField(max_length=255)

    def __unicode__(self):
        return self.tip_description


class Report(models.Model):
    """
    User reports. These are custom reports the user sets, and are different from the alerts
    """
    users = models.ManyToManyField(User, through='UserReports')
    report_type = models.CharField(max_length=128)

    def __unicode__(self):
        return self.report_type


class UserReports(models.Model):
    user_id = models.ForeignKey(User)
    report_id = models.ForeignKey(Report)
    occurrence_type = models.CharField(max_length=128)
    datetime = models.DateTimeField()
    report_daily = models.BooleanField()
    report_weekly = models.BooleanField()
    report_monthly = models.BooleanField()


class SocialMediaAccount(models.Model):
    """
    Social media account info for each user
    """
    user_id = models.ForeignKey(User)
    account_type = models.CharField(max_length=255)
    account_token = models.CharField(max_length=255)
    account_token_secret = models.CharField(max_length=255)
    account_auth_verify = models.CharField(max_length=255)
    post_daily = models.BooleanField()
    post_weekly = models.BooleanField()
    post_monthly = models.BooleanField()
    post_yearly = models.BooleanField()
    is_enabled = models.BooleanField()

    def __unicode__(self):
        return self.account_type


class Food(models.Model):
    """
    Food items. A list of all possible food products will be kept
    """
    food_description = models.CharField(max_length=255)
    food_spoiltime = models.TimeField()

    def __unicode__(self):
        return self.food_description


class HouseFoods(models.Model):
    """
    Food products for the household
    """
    food_id = models.ForeignKey(Food)


class ElectricityType(models.Model):
    """
    Setup what type of electricity plan the household has
    """
    plan_type = models.CharField(max_length=128)

    def __unicode__(self):
        return self.plan_type


class PrepaidTopups(models.Model):
    """
    Prepaid topups for the household
    """
    topup_date = models.DateTimeField(primary_key=True)
    topup_amount = models.FloatField()
    topup_units = models.IntegerField()


class PostPaid(models.Model):
    unit_cost = models.FloatField()


class Configuration(models.Model):
    """
    A class storing miscellaneous properties about the household
    """
    field = models.CharField(max_length=255, primary_key=True)
    value = models.IntegerField(default=0)


class EskomStats(models.Model):
    field = models.CharField(max_length=255, primary_key=True)
    value = models.CharField(max_length=255)

powermonitorweb/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.db import connection
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.views import password_change, password_reset, password_reset_confirm, password_reset_complete
from django.core import serializers
from django.core.urlresolvers import reverse

from powermonitorweb.forms import UserForm, SelectGraphPeriodForm
from powermonitorweb.forms import HouseholdSetupUserForm, SocialMediaAccountForm, ReportTypeForm, ReportDetailsForm, \
    ManageUsersForm, UserListForm, ProfileForm, UserAlerts, AlertTypeForm, AlertDetailsForm
from powermonitorweb.models import Report, ElectricityType, User, UserReports, Alert, UserAlerts
from powermonitorweb.utils import createmessage
# requirements for graphing
from DataAnalysis.Stats import PowerForecasting as forecast
from DataAnalysis.Plotting import Plotter as plt
from DataAnalysis.DataFrameCollector import DataFrameCollector as dfc
from Externals.PowerAlertScraper import PowerAlertScraper as PAS
from DataAnalysis.Resampling import Resampling
from datetime import datetime
from dateutil.relativedelta import relativedelta
import os

# No need to assert login here, this view just redirects to an appropriate page
def index(request):
    # Check if the household has been set up. If it hasn't, redirect to setup_household
    cursor = connection.cursor()
    cursor.execute("SELECT value FROM powermonitorweb_configuration WHERE field='is_setup'")
    norow = False
    is_setup = cursor.fetchone()
    if is_setup is None:
        setup = False
        norow = True
    else:
        setup = bool(is_setup[0])
    # If the household has not been setup, redirect to setup_household
    if not setup:
        return HttpResponseRedirect('/powermonitorweb/setup_household')
    # If the household has been setup, this will fall through to the next redirect below
    return HttpResponseRedirect('/powermonitorweb/graphs/')  # start at the graphs page


def setup_household(request):
    """
    Setup up the household profile
    REQUIRED:   The database table powermonitorweb_configuratin must have data. This should be set up when the system
                is deployed and should not require intervention from the user.
    """
    context = RequestContext(request)
    electricity_type = ElectricityType.objects.all()
    cursor = connection.cursor()
    cursor.execute("SELECT value FROM powermonitorweb_configuration WHERE field='is_setup'")
    norow = False
    issetup = cursor.fetchone()
    if issetup is None:
        setup = False
        norow = True
    else:
        setup = bool(issetup[0])
    
    if setup:
        return HttpResponseRedirect('/powermonitorweb/')

    if request.method == 'POST':
        setup_homeowner_form = HouseholdSetupUserForm(data=request.POST)

        elec = request.POST['electricity_type']

        if setup_homeowner_form.is_valid():
            homeowner = setup_homeowner_form.save()
            homeowner.set_password(homeowner.password)
            homeowner.is_superuser = True
            homeowner.save()

            if norow:
                cursor.execute("INSERT INTO powermonitorweb_configuration(field, value) VALUES ('is_setup',1)")
            else:
                cursor.execute("UPDATE powermonitorweb_configuration SET value=1 WHERE field='is_setup'")
            setup = True
        else:
            print setup_homeowner_form.errors
    else:
        setup_homeowner_form = HouseholdSetupUserForm()

    return render_to_response(
        'powermonitorweb/setup_household.html',
        {'setup_homeowner_form': setup_homeowner_form,
         'electricity_type': electricity_type,
         'setup': setup},
        context)

def user_login(request):
    context = RequestContext(request)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:  # added this in case we want to use this functionality
                login(request, user)
                return HttpResponseRedirect('/powermonitorweb/')
            else:
                return HttpResponse('This account is disabled')
        else:
            return render_to_response(
                'powermonitorweb/invalid_login.html',
                {'username': username},
                context
            )
    else:
        return render_to_response('powermonitorweb/login.html', {}, context)


@login_required()   # You can only logout if you're already logged in...obviously
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/powermonitorweb/')


from powermonitorweb.models import SocialMediaAccount
pending_social_accounts = {}
@login_required()
def manage_social_media(request):
    """
    Display options for the user to select which social media to post to.
    """
    # TODO: This needs to be complete once we are actually able to post to social media sites
    context = RequestContext(request)

    user = request.user
    user_accounts = SocialMediaAccount.objects.all().filter(user_id=user.id)
    
    if request.is_ajax():
        datadict = request.POST
        if datadict.get('identifier') == 'delete_account_click':
            account = SocialMediaAccount.objects.get(id=datadict.get('id_account_type'))
            if account:
                account.delete()
                JSONdata = '{"deleted": true}'
            else:
                JSONdata = '{"deleted": false}'
        return HttpResponse(JSONdata)
    elif request.method == 'POST':
        if request.POST.get('network'):
            network=request.POST.get('network')
            #this is an add
            # redirect to the social network for approval
            if network == 'Facebook':
                raise NotImplementedError("Facebook login has not been implemented yet")
            elif network == 'Twitter':
                from Externals import Twitter
                twitter = pending_social_accounts[(user.id, network)] = Twitter.Twitter()
                print request.get_host()+"/auth_social_media"
                return HttpResponseRedirect(twitter.authorize("http://%s/powermonitorweb/auth_social_media"%request.get_host()))

    else:
       account = request.POST.get('account_select')
       posts = request.POST.getlist('posts')
       period = request.POST.get('period_select')
       
       if any(posts):
           '''If any of the checkboxes are checked, then we can do something.'''
           if 'current_usage' in posts:
               # TODO: Post current usage to selected social media
               pass
           if 'average_usage' in posts:
               # TODO: Post average usage to selected social media
               pass
           if 'savings' in posts:
               # TODO: Post savings to selected social media
               pass
           if 'graph' in posts:
               # TODO: Post graph of usage to selected social media
               pass
       else:
           pass

       return render_to_response(
           'powermonitorweb/manage_social_media.html',
           {'user_accounts': user_accounts},
           context
       )

def auth_social_media(request):
    #try to detect the network we're getting a redirect from
    if request.GET.get('oauth_token'):
        network = 'Twitter'
    else:
        network = 'Facebook'
    
    user = request.user
    if (user.id,network) not in pending_social_accounts:
        raise EnvironmentError("How are we getting responses for networks we aren't trying to authorize?")
    else:
        if network == 'Facebook':
            raise NotImplementedError()
        else:
            twitter = pending_social_accounts[(user.id,network)]
            # todo error handling - do we need it?
            twitter.authorize_receive(oauth_token=request.GET.get('oauth_token'),
                                      oauth_verifier=request.GET.get('oauth_verifier'))
            account_token=twitter.request_token
            account_token_secret=twitter.request_token_secret
            account_auth_verify=twitter.authorized_verifier
            del pending_social_accounts[(user.id,network)]

        social_media_account = SocialMediaAccount(
            user_id=user,
            account_type=network,
            account_token=account_token,
            account_token_secret=account_token_secret,
            account_auth_verify=account_auth_verify,
            post_daily=False,
            post_weekly=False,
            post_monthly=False,
            post_yearly=False,
            is_enabled=False)
        social_media_account.save()
        return HttpResponseRedirect("/powermonitorweb/manage_social_media/")


@login_required()
def manage_alerts(request):
    context = RequestContext(request)
    posted = False

    user = request.user
    user_alerts = UserAlerts.objects.all().filter(user_id=user.id)
    alerts = Alert.objects.all()
    user_alert_details = None

    if request.is_ajax():
        datadict = request.POST

        if datadict.get('identifier') == 'id_alert_type_change':

            myalert = alerts.filter(id=datadict.get('alert_type'))
            if len(myalert) == 1:
                JSONdata = serializers.serialize('json', myalert, fields=('alert_description',))
            else:
                # send blank fields to override values as a reset mechanism
                JSONdata = '{ "fields":{"alert_description" : ""}}'
        elif datadict.get('identifier') == 'enable_alert_click':
            try:
                rec_alert_id = Alert.objects.get(id=int(datadict.get('alert_type')))

powermonitorweb/templates/powermonitorweb/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <script type="text/javascript" src="{% static '/static/powermonitorweb/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static '/static/powermonitorweb/bootstrap.js' %}"></script>
        <script type="text/javascript" src="{% static '/static/powermonitorweb/scripts.js' %}"></script>
        <link rel="shortcut icon" type="image/png" href="{% static '/static/powermonitorweb/images/icon.png' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static '/static/powermonitorweb/plugins/jquery.datetimepicker.css' %}"/>
        <link  rel="stylesheet" type="text/css" href="{% static '/static/powermonitorweb/mainstyle.css' %}"/>
        <title>Power Monitor - {% block title %}Intelligent Power Monitoring{% endblock %}</title>
    </head>
    <body>
        <div id="content_wrapper">
            <div id="main">
                <div id="imageholder">
                    <a href="/powermonitorweb/" id="homepage-link"><h1>Power Monitor</h1></a>
                    <ul id="bar">
                        <li class="pull-left">
                            <a href="/powermonitorweb/graphs/">
                                <div class="pull-left">
                                    <img class="icon" alt=""  src="{% static '/static/powermonitorweb/images/graphs_icon.svg' %}" />
                                </div>
                                <div class="pull-left bar-heading">Graphs</div>
                            </a>
                        </li>
                        <li class="pull-left">
                            <a href="#">
                                <div class="pull-left">
                                    <img class="icon" alt=""  src="{% static '/static/powermonitorweb/images/food_icon.svg' %}" />
                                </div>
                                <div class="pull-left bar-heading">Food</div>
                            </a>
                        </li>
                        <li class="pull-left">
                            <a href="/powermonitorweb/manage_alerts/">
                                <div class="pull-left">
                                    <img class="icon" alt=""  src="{% static '/static/powermonitorweb/images/alerts_icon.svg' %}" />
                                </div>
                                <div class="pull-left bar-heading">Alerts</div>
                            </a>
                        </li>
                        <li class="pull-left">
                            <a href="/powermonitorweb/manage_reports/">
                                <div class="pull-left">
                                    <img class="icon" alt=""  src="{% static '/static/powermonitorweb/images/reports_icon.svg' %}" />
                                </div>
                                <div class="pull-left bar-heading">Reports</div>
                            </a>
                        </li>
                        <li class="pull-left">
                            <a href="/powermonitorweb/manage_social_media/">
                                <div class="pull-left">
                                    <img class="icon" alt=""  src="{% static '/static/powermonitorweb/images/social_icon.svg' %}" />
                                </div>
                                <div class="pull-left bar-heading">Social</div>
                            </a>
                        </li>
                        {% if user.is_superuser %}
                        <li class="pull-left">
                            <a href="/powermonitorweb/manage_users/">
                                <div class="pull-left">
                                    <img class="icon" alt=""  src="{% static '/static/powermonitorweb/images/users_icon.svg' %}" />
                                </div>
                                <div class="pull-left bar-heading">Users</div>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                    <!-- source: http://www.turbophoto.com/Free-Images/tag/polar-bear/ -->
                    <img id="lizard" alt="monitor lizard" height="165" src="{% static '/static/powermonitorweb/images/MonitorLizard.png' %}" />
                </div>
                <div id="userdetails">
                    <div class="pull-right marginfive">Welcome, <span id="username">{{user.first_name}}<span class="caret" id="downarrow"></span></span>
                        <div id="usermenu">
                            <ul>
                                <li><a href="/powermonitorweb/profile/">Change Profile</a></li>
                                <li><a href="/powermonitorweb/logout/">Logout</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                {%block main %}
                {% endblock %}
                
            </div>
            <div id="push"></div><!-- for the footer to stay at the bottom of the page -->
        </div>
        <div id="footer">
            <small>
                {% block footer %}
                Copyright &copy; EcoBerry 2014
                {% endblock %}
            </small>
        </div>
    </body>
</html>

powermonitorweb/templates/powermonitorweb/change_password.html
{% extends 'powermonitorweb/base.html' %}
{% block title %}Change Password{% endblock %}

{% block header %}Change Password{% endblock %}
{% block main %}
    <div class="panel panel-default">
        <div class="panel-heading"><h3>Change Password</h3></div>
        <form class="panel-body" method="post" action=".">
            {% csrf_token %}
            <div class="listform">
                {{ form.as_p }}
            </div>
            <div class="listform">
                <p>
                    <a class="form-right" href="/powermonitorweb/profile/">Go back</a>
                </p>
                <p>
                    <input class="btn btn-success form-right" type="submit" value="Change" />
                </p>
            </div>
        </form>
    </div>
{% endblock %}

powermonitorweb/templates/powermonitorweb/graphs.html
{% extends 'powermonitorweb/base.html' %}
{% load staticfiles %}
{% block title %}Graphs{% endblock %}

{% block header %}Usage Graphs{% endblock %}
{% block main %}
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <script src="{% static '/static/powermonitorweb/scripts/graphs.js' %}" ></script>
    <div class="panel panel-default">
        <div class="panel-heading"><h3>Graphs</h3></div>
        <div class="panel-body">
            <div>
                Select the period you wish to view:
                {{ graph_period_form.as_p }}
            </div>
        <div id="chart_div" style="width:100%; height:500px;">
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading"><h3>Metrics</h3></div>
        <div id="panel-body">
            <div id="current_usage" class="metric panel panel-primary col-xs-3">
                <div class="panel-heading"><h4>Current Usage:</h4></div>
                <p class="panel-body">
                    {% if current_usage != None %}
                    {{ current_usage }} W
                    {% else %}
                    No data available.
                    {% endif %}
                </p>
            </div>
            <div id="average_usage" class="metric panel panel-primary col-xs-3">
                <div class="panel-heading"><h4>Average Usage Per Hour:</h4></div>
                <p class="panel-body">
                    {% if average_usage != None %}
                    {{ average_usage }} W
                    {% else %}
                    No data available.
                    {% endif %}
                </p>
            </div>
            <div id="eskom_status" class="metric panel panel-primary col-xs-3">
                <div class="panel-heading"><h4>Country Power Rating:</h4></div>
                    <div class="panel-body">
                        {% if eskom_status != None %}
                        <div id="eskom_image">
                            <div class="center-helper"></div>
                            <img src="{{ STATIC_URL }}powermonitorweb/images/{{ eskom_status }}" alt="" width="50%" />
                        </div>
                        {% else %}
                        <p>
                            No data available.
                        </p>
                        {% endif %}
                    </div>
            </div>
            <div id="savings" class="metric panel panel-primary col-xs-3">
                <div class="panel-heading"><h4>Your Savings:</h4></div>
                <p class="panel-body">
                    {% if savings != None %}
                    R {{ savings }}
                    {% else %}
                    No data available.
                    {% endif %}
                </p>
            </div>
            <div id="clearfloat"></div>
        </div>
    </div>
{% endblock %}

powermonitorweb/templates/powermonitorweb/invalid_login.html
{% extends 'powermonitorweb/login_base.html' %}
{% block title %}Failed Login{% endblock %}

{% block header %}Sign in{% endblock %}
{% block main %}
<div class="panel panel-default">
    <div class="panel-heading"><h3>Sign in</h3></div>
    <div class="panel-body">
        <div class="alert alert-danger">
            <strong>Invalid Login</strong>
            Invalid username or password for '{{ username }}'.
        </div>
        <form id="login_form" class="panel-body" method="post" action="/powermonitorweb/login/">
            {% csrf_token %}
            <div class="listform">
                <p><label for="username">Username:</label> <input type="text" name="username" value="{{ username }}"/></p>
                <p><label for="passwd">Password:</label> <input type="password" name="password"/></p>
            </div>
            <div class="listform">
                <p>
                    <a class="form-right" href="/powermonitorweb/reset_password/">Forgot your password?</a>
                </p>
                <p>
                    <input class="btn btn-success form-right" type="submit" value="Login"/>
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

powermonitorweb/templates/powermonitorweb/login.html
{% extends 'powermonitorweb/login_base.html' %}
{% block title %}Login{% endblock %}

{% block header %}Sign in{% endblock %}
{% block main %}
<div class="panel panel-default">
    <div class="panel-heading"><h3>Sign in</h3></div>
    <form id="login_form" class="panel-body" method="post" action="/powermonitorweb/login/">
        {% csrf_token %}
        <div class="listform">
            <p><label for="username">Username:</label> <input type="text" name="username"/></p>
            <p><label for="passwd">Password:</label> <input type="password" name="password"/></p>
        </div>
        <div class="listform">
            <p>
                <a class="form-right" href="/powermonitorweb/reset_password/">Forgot your password?</a>
            </p>
            <p>
                <input class="btn btn-success form-right" type="submit" value="Login"/>
            </p>
        </div>
    </form>
</div>
{% endblock %}

powermonitorweb/templates/powermonitorweb/manage_users.html
{% extends 'powermonitorweb/base.html' %}
{% load staticfiles %}
{% block title %}Manage Users{% endblock %}

{% block header %}Manage Powermonitor Users{% endblock %}
{% block main %}
    <script src="{% static '/static/powermonitorweb/scripts/manage_users.js' %}" ></script>
    {% if failed %}
    <strong>Something went wrong updating user.</strong>
    {% else %}
    {% if posted %}
    <strong>User settings saved!</strong>
    {% else %}
    <div class="panel panel-default">
        <div class="panel-heading"><h3>Manage Users</h3></div>
	<div id="error-container" class="panel-body panel-nobottom"></div>
        <form class="panel-body fillparenttarget" id="manage_users_form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="manage_form" class="pull-left col-xs-6 fillparent">
                <div class="panel panel-primary listlayout">
                    <div class="panel-heading"><h2>All Users</h2></div>
                    <p class="panel-body">{{ user_list_form.users }}
                        <div class="buttons">
                            <input type="button" class="btn btn-success" id="add_user" name="add" data-toggle="modal" data-target="#add_form"value="Add User" />
                            <input type="button" class="btn btn-danger" id="delete_user" name="delete" value="Delete User" />
                        </div>
                    </p>
                </div>
            </div>
            <div class="pull-left col-xs-6 fillparent">
                <div id="display" class="panel panel-primary">
                    <div class="panel-heading"><h2>Selected User</h2></div>
                    <div class="miniform panel-body">
                        {{ manage_users_form.as_p }}
                        {{ manage_users_form.errors }}
                        <input class="btn btn-primary form-right" type="button" id="update_user" name="add" value="Update" /><br />
                        <br/>
                        <p>
                            <label for="reset_password">Send password reset email</label>
                            <input class="btn btn-warning" type="button" id="reset_password" name="reset_password" value="Reset Password" />
                        </p>
                    </div>
                </div>
            </div>
        </form>
        <div id="add_form" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title">Add User</h4>
                    </div>
                    <div id="add_form_body" class="modal-body">
                        <!-- the form is added here with ajax -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endif %}
{% endblock %}

powermonitorweb/templates/powermonitorweb/not_admin.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Power Monitor</title>
</head>
<body>
    <h1>Sorry, you are not an admin!</h1>
    <select name="sometext" size="5">
  <option>text1</option>
  <option>text2</option>
  <option>text3</option>
  <option>text4</option>
  <option>text5</option>
</select>
</body>
</html>

powermonitorweb/templates/powermonitorweb/reset_password.html
{% extends 'powermonitorweb/login_base.html' %}
{% block title %}Reset Password{% endblock %}

{% block main %}
<form method="post">
    {% csrf_token %}
    <div class="formlayout">
        <p>Enter the email address associated with your account</p>
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </div>
</form>
{% endblock %}

powermonitorweb/templates/powermonitorweb/reset_password_email.html
Someone asked for password reset for email {{ email }} for Power Monitor. Follow the link below:
{{ protocol}}://{{ domain }}{% url "powermonitorweb:reset_password_confirm" uidb64=uid token=token %}